# The URL the site will be built for
base_url = "https://marcosba.github.io"
title = "Marcos Blog"

theme = "duckquill"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here

[extra.nav]
# Whether to automatically hide nav when not hovered or focused
# auto_hide = true
# Whether to show the Atom/RSS feed button in the nav
show_feed = true
# Whether to show the manual theme switcher in the nav
show_theme_switcher = true
# Whether to show the link to the source repository in the nav
show_repo = true
# Links used in the nav.
# For local files use same link format as in Markdown,
# i.e. "@/blog/_index.md".
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
	{ name = "Links", menu = [
		{ url = "@/blog/_index.md", name = "Blog" },
		{ url = "@/demo/index.md", name = "Demo" },
		{ url = "@/mods/index.md", name = "Mods" }
	] },
	{ url = "https://daudix.one/coffee/", name = "Coffee" }
]